/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstancesInstanceTabRouteImport } from './routes/instances/$instance/$tab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesInstanceTabRoute = InstancesInstanceTabRouteImport.update({
  id: '/instances/$instance/$tab',
  path: '/instances/$instance/$tab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instances/$instance/$tab': typeof InstancesInstanceTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instances/$instance/$tab': typeof InstancesInstanceTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instances/$instance/$tab': typeof InstancesInstanceTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/instances/$instance/$tab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/instances/$instance/$tab'
  id: '__root__' | '/' | '/instances/$instance/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstancesInstanceTabRoute: typeof InstancesInstanceTabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/$instance/$tab': {
      id: '/instances/$instance/$tab'
      path: '/instances/$instance/$tab'
      fullPath: '/instances/$instance/$tab'
      preLoaderRoute: typeof InstancesInstanceTabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstancesInstanceTabRoute: InstancesInstanceTabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
